version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/nginx_deploy/zip/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: stop.sh
      timeout: 240
      runas: ec2-user

  ApplicationStart:
    - location: start.sh
      timeout: 240
      runas: ec2-user

  ValidateService:
    - location: validate.sh
      timeout: 240
      runas: ec2-user